title: SOOYEON Page
email: ksy9500@naver.com
author:
  picture: http://cdn.shopify.com/s/files/1/0035/2754/0782/articles/International_Flower_Day_1200x1200.jpeg?v=1579365491 
  name: KIM SOOYEON
  location: Seongnamsi - Korea
  description: "A Future professional developer"  
description: MY PORTFOLIO
baseurl: "/"
url: https://dduyon2.github.io/
github_username: dduyon2
github_url: https://dduyon2.github.io/

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
