title: SOOYEON Page
email: ksy9500@naver.com
author:
  picture: http://site.hugocarreira.me/assets/img/compressed/hugo.jpg #URL FORMAT
  name: Hugo Carreira
  location: Rio de Janeiro - Brazil
  description: "19 years old, studying computer science"  
description: only my simple vision of casper theme
baseurl: "/"
url: https://hugocarreira.github.io/jekyll-vision-casper-theme
twitter_username: 
github_username: dduyon2
github_url: https://hugocarreira.github.io/jekyll-vision-casper-theme/

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
